default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: desafio_api_desarrollo

test:
  <<: *default
  database: desafio_api_test

production:
  <<: *default
  database: desafio_api_produccion
  username: desafio_api
  password: <%= ENV['DESAFIO_API_DATABASE_PASSWORD'] %>