default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: desafio_api_desarrollo

test:
  <<: *default
  database: desafio_api_test

production:
  <<: *default
  database: desafio_api_produccion
  password: <%= ENV['RUBY-GETTING-STARTED_DATABASE_PASSWORD'] %>