# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b4caee1e5f87727a5968935cec334cf0ffdfc6ee2660b251e1cb29169fb5cb27a944eef1ad2b50572e102e7d7e54a2f586bd914628d6fbdbaeb148e0b980ea20

test:
  secret_key_base: 8aaa32d42dbacfd28b6c1a6ba55317998eb6b155a95de016ace3428bfcf0dd0fe872c829059b57a717a072f3277d0dd8f4b93470baf9362f9bb454b63988cb22

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
